# https://dev.to/alex_barashkov/using-docker-for-nodejs-in-development-and-production-3cgp

FROM node:15-alpine

ARG NODE_ENV=development
ENV NODE_ENV=${NODE_ENV}

RUN apk --no-cache add python make g++ ffmpeg

COPY package*.json ./
RUN npm install -g typescript

WORKDIR /usr/src/app
