on: [push]

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    name: Build prod
    environment: Prod
    steps:
      - uses: kciter/aws-ecr-action@master
        with:
          access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          account_id: ${{ secrets.AWS_ACCOUNT_ID }}
          repo: 362237326312.dkr.ecr.eu-west-3.amazonaws.com/ptitloupbot
          region: eu-west-3
          tags: latest,${{ github.sha }}
          create_repo: true
